model:
  base_learning_rate: 1.0e-04
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: caption
    image_size: 64
    channels: 4
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.05
    use_ema: true
    
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 256
        attention_resolutions: [ 4, 2, 1 ]
        num_res_blocks: 3
        channel_mult: [ 1, 2, 4, 4 ]
        num_heads: 8
        use_spatial_transformer: true
        transformer_depth: 1
        use_checkpoint: True
        context_dim: 512
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        embed_dim: 4
        ckpt_path: <path/to/ocr-vqgan-encoder.ckpt>
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: ldm.modules.encoders.modules.BERTEmbedder
      params:
        n_embed: 512
        n_layer: 128
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 8
    num_workers: 2
    wrap: false
    train:
      target: ldm.data.paper2fig.Paper2FigTrain
      params:
        json_file: <path/to/paper2fig_train.json>
        size: 512
        caption_modality: 0
        random_crop: false
        square_pad: True
    validation:
      target: ldm.data.paper2fig.Paper2FigValidation
      params:
        json_file: <path/to/paper2fig_test.json>
        size: 512
        caption_modality: 0
        random_crop: false
        square_pad: True
    test:
      target: ldm.data.paper2fig.Paper2FigValidation
      params:
        json_file: <path/to/Paper2Fig100k/paper2fig_test.json>
        size: 512
        caption_modality: 0
        random_crop: false
        square_pad: True
lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 100
        max_images: 4
        increase_log_steps: false
  trainer:
    accumulate_grad_batches: 1
    benchmark: true
    accelerator: ddp
    gpus: 0,